language: cpp
os: 
  - linux
compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ trusty main universe"
  - sudo apt-get update
  - sudo apt-get install clang
  - sudo apt-get install g++
  - sudo apt-get install libhdf5-7
  - sudo apt-get install libpango-1.0-0 libpangocairo-1.0-0 libhdf5-dev
  - sudo apt-get install -t trusty -y libboost-thread-dev libboost-timer-dev libblitz0-dev gnuplot-nox libhdf5-serial-dev cmake libgnuplot-iostream-dev

before_script:
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=RELEASE ../

script:
    - make

#after_script:
#    - make test
